image: ruby:2.6-alpine

stages:
  - build
  - docker
  - deploy

build:
  stage: build
  artifacts:
    paths:
      - ./build
  script:
    - bundle install --deployment
    - bundle exec middleman build

docker:
  stage: docker
  image: docker:git
  services:
    - docker:dind
  dependencies:
    - build
  script:
    - docker login registry.gitlab.com -u rocky-jaiswal -p $GITLAB_TOKEN
    - docker build -t registry.gitlab.com/rocky-jaiswal/my_blogs:$CI_COMMIT_SHA .
    - docker push registry.gitlab.com/rocky-jaiswal/my_blogs:$CI_COMMIT_SHA

deploy:
  stage: deploy
  script:
    - 'echo "{\"token\": \"$GITLAB_TOKEN\"}" > token.json'
    - 'cat token.json'
    - 'curl -X POST https://wortschatz.live/__deployer/session -H "Authorization: Basic $DEPLOYER_AUTH" -H "Content-Type: application/json" --data @token.json'
    - 'echo "{\"service-name\": \"my_blogs\"," > deploy.json'
    - 'echo "\"image-path\": \"registry.gitlab.com/rocky-jaiswal/my_blogs:$CI_COMMIT_SHA\"}" >> deploy.json'
    - 'cat deploy.json'
    - 'curl -X POST https://wortschatz.live/__deployer/deployment -H "Authorization: Basic $DEPLOYER_AUTH" -H "Content-Type: application/json" --data @deploy.json'
