image: ruby:2.3

stages:
  - build
  - docker
  - deploy

build:
  stage: build
  artifacts:
    paths:
      - ./build
  script:
    - bundle install --deployment
    - bundle exec middleman build

docker:
  stage: docker
  image: docker:git
  services:
    - docker:dind
  dependencies:
    - build
  script:
    - docker login registry.gitlab.com -u rocky-jaiswal -p $GITLAB_TOKEN
    - docker build -t registry.gitlab.com/rocky-jaiswal/my_blogs:$CI_JOB_ID .
    - docker push registry.gitlab.com/rocky-jaiswal/my_blogs:$CI_JOB_ID

deploy:
  stage: deploy
  script:
    - 'curl -X GET https://test-sandbox.live/deployer/health -H "Authorization: Basic $DEPLOYER_AUTH"'
    - 'curl -X PUT https://test-sandbox.live/deployer/service -H "Authorization: Basic $DEPLOYER_AUTH" -H "Content-Type: application/json" --data {"service-name": "my-blogs", "image-name": "BLOG_IMAGE_ID", "image-id": "$CI_JOB_ID"}'
